/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sk.project8

import com.sk.project8.annotation.BuilderProcessor
import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class AppTest {

    var uid = 0

    @Test
    fun whenBuildPropertiesWithPriority0() {
        val result = compileAndGenerateResult("""@com.sk.project8.annotation.BuilderProperty(priority = 0)""")
        println(result.messages)
        assertThat(result.messages).contains("Need to change priority")
        assertThat(result.exitCode).isEqualTo(KotlinCompilation.ExitCode.OK)
    }

    @Test
    fun whenBuildPropertiesWithPriority1() {
        val result = compileAndGenerateResult("""@com.sk.project8.annotation.BuilderProperty(priority = 1)""")

        assertThat(result.messages).contains("Good priority")
        assertThat(result.exitCode).isEqualTo(KotlinCompilation.ExitCode.OK)
    }

    @Test
    fun whenBuildPropertiesWithPriority_1() {
        val result = compileAndGenerateResult("""@com.sk.project8.annotation.BuilderProperty(priority = -1)""")

        assertThat(result.messages).contains("Priority cannot be negative")
        assertThat(result.exitCode).isEqualTo(KotlinCompilation.ExitCode.COMPILATION_ERROR)
    }

    private fun compileAndGenerateResult(annotations: String): KotlinCompilation.Result {
        return compileAndGenerateResult(createSourceFile(annotations))
    }

    private fun compileAndGenerateResult(kotlinSource: SourceFile): KotlinCompilation.Result {
        return KotlinCompilation().apply {
            sources = listOf(kotlinSource)
            annotationProcessors = listOf(BuilderProcessor())
            inheritClassPath = true
            messageOutputStream = System.out
        }.compile()
    }

    private fun createSourceFile(annotations: String): SourceFile {
        uid = uid + 1
        return SourceFile.kotlin(
            "KClass.kt", """
            package com.sk.project8.model           

           class KClass$uid() {
             $annotations
                 fun setName(name: String) {
                 }
                 
                 fun setAge(age: Int) {
                 }
           }
        """.trimIndent()
        )
    }
}
