#spring.cloud.gateway.default-filters[1]: AddResponseHeader=my-custom-header-0, my-custom-header-0-value

server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
#      default-filters:
#        - AddResponseHeader=my-custom-header-1, my-custom-header-1-value
      routes:
        - id: after_route
          uri: http://localhost:81
          predicates:
            - Path=/after_route
          filters:
          #- StripPrefix=1
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 4
              redis-rate-limiter.requestedTokens: 4
              key-resolver: "#{@keyResolver1}"
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 60
              redis-rate-limiter.requestedTokens: 60
              key-resolver: "#{@keyResolver2}"
        - id: websocket-test-endpoint
          uri: http://localhost:8080
          predicates:
            - Path=/websocket-test-endpoint/api/**
            - QueryParam=Authorization
          filters:
            - RewritePath=/websocket-test-endpoint/api/(?<segment>.*), /websocket-test-endpoint/api/$\{segment}
            - AddRequestHeader=Authorization, {Authorization}
        - id: websocket-test
          uri: http://localhost:8080
          predicates:
            - Path=/websocket-test/resources/**
          filters:
            - RewritePath=/websocket-test/resources/(?<segment>.*), /websocket-test/resources/$\{segment}
        - id: priority_test_regex
          uri: http://localhost:80
          order: 1
          predicates:
            - Path=/route/**
          filters:
            - RewritePath=/route/(?<segment>.*), /$\{segment}
        - id: priority_test_simple
          uri: http://localhost:80
          order: 0
          predicates:
            - Path=/route/simple
          filters:
            - RewritePath=/route/simple, /get?name=simple
        - id: ms_graph
          uri: https://graph.microsoft.com
          order: 0
          predicates:
            - Path=/graph/**
          filters:
            - RequestLog
            - RewritePath=/graph/(?<segment>.*), /v1.0/$\{segment}


management:
  health:
    redis:
      enabled: true
  endpoint:
    gateway:
      enabled:true
  endpoints:
    web:
      exposure:
        include: gateway

#debug: true
#logging:
#  level:
#    web: DEBUG

##      filter:
##        request-rate-limiter:
##          deny-empty-key: false  # no key resolver needed

# run redis
# docker run -d --name redis -p 6379:6379 redis